### ISSUE TITLE
DragonAPI patch no longer works on newer cauldron builds

### ISSUE THREAD

**Issue by devryb** [TCPR/Fixes#2]
In cauldron builds starting around 185 the dragonapi patch is no longer working.

Noted here in the bug report: https://gitlab.prok.pw/KCauldron/KCauldron/issues/337

**Comment by Robotia** [comment]
@devryb I am sorry but we refuse to support DragonAPI, as is stated on the README.
DragonAPI makes changes that are not easy to handle.

**Comment by ajthemacboy** [comment]
Reika's mods are just insanely unstable and unoptomized... I don't blame you :P
